spring.application.name=LoginRegistration

# hibernate properties
spring.datasource.url=jdbc:mysql://localhost:3306/coditas
spring.datasource.username=root
spring.datasource.password=showdata
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
